-- 1. Total number of rides
SELECT COUNT(*) AS total_rides
FROM ola_clean;

-- 2. Completed vs Cancelled rides
SELECT status, COUNT(*) AS ride_count
FROM ola_clean
GROUP BY status;

-- 3. Revenue generated by each payment method
SELECT payment_method, SUM(total_amount) AS total_revenue
FROM ola_clean
GROUP BY payment_method
ORDER BY total_revenue DESC;

-- 4. Average ride distance per vehicle type
SELECT vehicle_type, ROUND(AVG(distance_km),2) AS avg_distance_km
FROM ola_clean
GROUP BY vehicle_type
ORDER BY avg_distance_km DESC;

-- 5. Top 5 customers by spending
SELECT customer_id, SUM(total_amount) AS total_spent
FROM ola_clean
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 5;

-- 6. Daily ride volume (number of rides per day)
SELECT DATE(start_time) AS ride_date, COUNT(*) AS rides
FROM ola_clean
GROUP BY DATE(start_time)
ORDER BY ride_date;

-- 7. Average customer rating per vehicle type
SELECT vehicle_type, ROUND(AVG(customer_rating),2) AS avg_rating
FROM ola_clean
GROUP BY vehicle_type
ORDER BY avg_rating DESC;

-- 8. Cancellation breakdown (who cancelled more: customer vs driver)
SELECT cancelled_by_norm AS cancelled_by, COUNT(*) AS total_cancellations
FROM ola_clean
WHERE status_norm = 'Cancelled'
GROUP BY cancelled_by_norm;

-- 9. Peak booking hours (rides per hour of day)
SELECT HOUR(start_time) AS booking_hour, COUNT(*) AS rides
FROM ola_clean
GROUP BY HOUR(start_time)
ORDER BY rides DESC;

-- 10. Revenue trend by city (if city column exists)
SELECT city, SUM(total_amount) AS total_revenue
FROM ola_clean
GROUP BY city
ORDER BY total_revenue DESC;
